export type SystemId = 'skeletal'|'muscular'|'arterial'|'venous'|'nervous'|'digestive'|'respiratory'|'urinary'|'reproductive'|'lymphatic'|'endocrine'|'integumentary'|'connective'|'sensory'|'cardiac';
export const SYSTEMS: {id:SystemId;name:string;color:string;description:string}[] = [
 {id:'skeletal',name:'Skeleton',color:'#e2d9ba',description:'Bones form the supporting framework of the body, protect organs, and provide attachment points for muscles. Their internal tissue also stores minerals and produces blood cells.'},
 {id:'muscular',name:'Muscles',color:'#a85b50',description:'Skeletal muscles generate movement by pulling on their attachments. Together with tendons, they move joints, stabilize posture, and produce heat.'},
 {id:'cardiac',name:'Heart',color:'#b96760',description:'The heart is a muscular pump with four chambers. Its valves direct blood forward through the pulmonary and systemic circuits.'},
 {id:'sensory',name:'Sensory organs',color:'#b0c8ce',description:'These structures contribute to special senses, including sight, hearing, and balance. Their specialized tissues detect stimuli and work with the nervous system to convey information.'},
 {id:'arterial',name:'Arteries',color:'#c05245',description:'The heart drives blood through the circulation. Arteries carry blood away from the heart to supply tissues or, in the pulmonary circuit, to the lungs.'},
 {id:'venous',name:'Veins',color:'#527c9f',description:'Veins return blood toward the heart. Superficial and deep networks collect blood from the tissues; the pulmonary veins bring oxygenated blood back from the lungs.'},
 {id:'nervous',name:'Nervous system',color:'#d8b565',description:'The brain, spinal cord, and peripheral nerves carry and process signals. They support sensation, movement, coordination, and automatic regulation of body functions.'},
 {id:'respiratory',name:'Respiratory',color:'#b98991',description:'The airways conduct air to the lungs, where oxygen and carbon dioxide move between air and blood. Breathing depends on pressure changes produced by respiratory muscles.'},
 {id:'digestive',name:'Digestive',color:'#b8916b',description:'The digestive tract breaks down food, absorbs nutrients and water, and moves waste onward. Accessory organs contribute bile and digestive enzymes.'},
 {id:'urinary',name:'Urinary',color:'#b47961',description:'The kidneys filter blood and regulate fluid, electrolyte, and acid–base balance. Urine travels through the ureters to the bladder and exits through the urethra.'},
 {id:'lymphatic',name:'Lymphatic',color:'#879f7c',description:'Lymphatic vessels return excess tissue fluid to the circulation. Lymph nodes and other lymphoid organs support immune surveillance and responses.'},
 {id:'endocrine',name:'Endocrine',color:'#c5a09a',description:'Endocrine organs release hormones into the blood to coordinate processes such as metabolism, growth, stress responses, and reproduction.'},
 {id:'reproductive',name:'Reproductive',color:'#bda098',description:'The male reproductive structures represented here contribute to sperm production, maturation, transport, and the production of sex hormones.'},
 {id:'integumentary',name:'Body surface',color:'#ba9b7d',description:'The body surface provides an outer anatomical reference. The integumentary system forms a protective barrier and contributes to sensation and temperature regulation.'},
 {id:'connective',name:'Connective tissue',color:'#aec3bb',description:'Cartilage, ligaments, and other connective tissues support, connect, and separate structures. Their roles include stabilizing joints and distributing mechanical loads.'},
];
export interface Part {id:string;name:string;conceptId:string;system:SystemId;chunk:number;positions:number;normals:number;indices:number;vertexCount:number;indexCount:number;bounds:[number[],number[]]}
export interface Concept {id:string;name:string;elements:string[]}
export interface Atlas {version:string;sex?:'male';source?:string;scope?:string;parts:Part[];concepts:Concept[];chunks:{url:string;bytes:number;gzip?:string;gzipBytes?:number}[];triangles:number}
export type View = 'three-quarter'|'front'|'back'|'side';
export interface SceneState {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];isolate:boolean;view:View;rotate:boolean;reset:number}
export const DEFAULT_VISIBLE:SystemId[] = ['cardiac','sensory','skeletal','muscular','arterial','venous','nervous','respiratory','digestive','urinary','lymphatic','endocrine','reproductive','connective'];
export const EXPLANATIONS:Record<string,string> = {
 'heart':'A muscular pump in the chest. Its right side sends blood to the lungs; its left side sends blood through the systemic circulation.',
 'liver':'A large organ beneath the right side of the diaphragm. It processes absorbed nutrients, produces bile, and synthesizes many proteins carried in the blood.',
 'brain':'The central organ of the nervous system. Its interconnected regions support perception, movement, memory, language, and the regulation of bodily functions.',
 'stomach':'A muscular chamber between the esophagus and small intestine. It stores and mixes food with acid and enzymes before releasing it into the duodenum.',
 'spleen':'A lymphoid organ in the upper left abdomen. It filters blood, removes aging blood cells, and participates in immune responses.',
 'pancreas':'An abdominal organ with digestive and endocrine roles. It supplies enzymes to the small intestine and releases hormones including insulin and glucagon.',
 'urinary bladder':'A muscular reservoir in the pelvis that stores urine arriving from the kidneys through the ureters.',
 'trachea':'The main airway connecting the larynx to the bronchi. Its cartilage supports keep the airway open during breathing.',
 'diaphragm':'A broad muscle separating the chest and abdomen. When it contracts, it increases chest volume and helps draw air into the lungs.',
 'kidney':'A paired organ in the posterior abdomen that filters blood, removes waste as urine, and helps regulate blood pressure, fluid balance, and electrolyte levels.',
 'small intestine':'The digestive tube between the stomach and large intestine, made up of the duodenum, jejunum, and ileum. Most nutrient absorption happens here.',
 'large intestine':'The final section of the digestive tract, running from the cecum to the rectum. It absorbs water and electrolytes and forms and stores stool.',
 'esophagus':'A muscular tube connecting the pharynx to the stomach. Coordinated contractions of its wall move swallowed food and liquid downward.',
 'gallbladder':'A small pouch beneath the liver that stores and concentrates bile, releasing it into the small intestine to help digest fats.',
 'adrenal gland':'A small endocrine gland atop each kidney. Its outer cortex produces steroid hormones and its inner medulla releases adrenaline and noradrenaline.',
 'spinal cord':'A long bundle of nerve tissue running through the vertebral column. It relays signals between the brain and the rest of the body and coordinates reflexes.',
 'tongue':'A muscular organ in the mouth that manipulates food during chewing and swallowing, contributes to speech, and carries taste receptors.',
 'appendix':'A narrow pouch attached to the cecum. Its exact function is debated, though it may contribute to immune surveillance of the gut.',
 'thymus':'A gland in the upper chest, most active in childhood, where immune T cells mature before circulating through the body.',
 'prostate':'A gland surrounding the urethra below the bladder. It produces part of the fluid that makes up semen.',
 'testis':'The paired male reproductive gland that produces sperm and testosterone.',
 'urethra':'The tube that carries urine from the bladder out of the body; in males it also carries semen during ejaculation.',
 'ureter':'One of a pair of tubes that carry urine from each kidney down to the urinary bladder.',
 'skin':'The body\u2019s largest organ, forming a protective barrier against injury and infection while helping regulate temperature and sensing touch, pain, and pressure.',
 'cornea':'The transparent, curved front surface of the eye. It refracts incoming light and provides the eye\u2019s protective outer window.',
 'lens':'The transparent structure behind the iris that fine-tunes focus by changing shape, projecting a sharp image onto the retina.',
 'cerebellum':'A structure at the back of the brain that fine-tunes movement, balance, and coordination.',
 'hypothalamus':'A small region at the base of the brain that links the nervous system to the endocrine system, regulating temperature, hunger, thirst, and hormone release.',
 'pituitary gland':'A pea-sized gland beneath the hypothalamus often called the body\u2019s "master gland" for the hormones it releases that control other endocrine glands.',
 'duodenum':'The first and shortest segment of the small intestine, where digestive juices from the pancreas and liver mix with partially digested food.',
 'jejunum':'The middle segment of the small intestine, specialized for absorbing nutrients from digested food.',
 'ileum':'The final and longest segment of the small intestine, which absorbs remaining nutrients, including vitamin B12 and bile salts, before joining the large intestine.',
 'cecum':'A pouch at the start of the large intestine where the small intestine joins it; the appendix is attached here.',
 'rectum':'The final section of the large intestine, which stores stool before it is eliminated through the anus.',
 'aorta':'The largest artery in the body, carrying oxygenated blood from the heart\u2019s left ventricle to the rest of the systemic circulation.',
 'portal vein':'A large vein that carries nutrient-rich blood from the digestive organs and spleen to the liver for processing.',
 'coronary artery':'One of the arteries that branch from the aorta to supply oxygenated blood to the heart muscle itself.',
 'skull':'The bony structure of the head that encloses and protects the brain and supports the structures of the face.',
 'vertebral column':'The spine, a chain of connected vertebrae that supports the trunk, protects the spinal cord, and allows the back to bend and twist.',
 'rib':'One of the curved bones that, together with the sternum and thoracic vertebrae, form the rib cage protecting the heart and lungs.',
 'sternum':'The flat bone at the center of the chest that anchors the ribs and protects underlying organs.',
 'clavicle':'The collarbone, a slender bone connecting the sternum to the shoulder blade and helping support the shoulder.',
 'scapula':'The shoulder blade, a flat triangular bone that anchors muscles moving the arm and forms part of the shoulder joint.',
 'humerus':'The long bone of the upper arm, running from the shoulder to the elbow.',
 'radius':'One of the two forearm bones, running along the thumb side from the elbow to the wrist.',
 'ulna':'One of the two forearm bones, running along the little-finger side and forming the main hinge of the elbow.',
 'femur':'The thigh bone, the longest and strongest bone in the body, connecting the hip to the knee.',
 'tibia':'The shinbone, the larger of the two lower-leg bones, bearing most of the body\u2019s weight below the knee.',
 'fibula':'The slender bone alongside the tibia in the lower leg, providing muscle attachment and ankle stability rather than bearing much weight.',
 'patella':'The kneecap, a small bone embedded in the tendon of the thigh muscle that protects the knee joint and improves leverage during leg extension.',
 'mandible':'The lower jawbone, the only movable bone of the skull, which holds the lower teeth and forms the jaw joint.',
 'left lung':'The left of the two lungs, slightly smaller than the right to make room for the heart. It exchanges oxygen and carbon dioxide with the blood.',
 'right lung':'The right of the two lungs, slightly larger than the left. It exchanges oxygen and carbon dioxide with the blood.',
 'inferior vena cava':'The large vein that returns deoxygenated blood from the lower body to the right atrium of the heart.',
 'superior vena cava':'The large vein that returns deoxygenated blood from the head, neck, and upper limbs to the right atrium of the heart.',
 'common carotid artery':'One of the major arteries of the neck that supplies blood to the head and brain before dividing into internal and external branches.',
 'internal carotid artery':'A branch of the common carotid artery that supplies blood mainly to the brain and the eye.',
 'external ear':'The visible part of the ear along with the ear canal, which gathers sound waves and directs them toward the eardrum.',
 'ascending colon':'The first section of the large intestine, rising on the right side of the abdomen from the cecum to the liver.',
 'descending colon':'The section of the large intestine that carries stool down the left side of the abdomen toward the sigmoid colon and rectum.',
 'transverse colon':'The section of the large intestine that crosses the upper abdomen from the ascending to the descending colon.',
};
export function explanation(name:string,system:SystemId){return EXPLANATIONS[name.toLowerCase()] ?? SYSTEMS.find(s=>s.id===system)?.description ?? '';}
