// Auto-generated Uzbek anatomical-name translator.
// Every named structure in the BodyParts3D atlas is composed from a fairly
// small, repeated anatomical vocabulary (sides, positions, organs, bones,
// Latin muscle-name components, etc). This module translates that vocabulary
// into Uzbek and recomposes "A of B" phrases using Uzbek genitive word order,
// so every one of the ~3,400 named structures gets a real Uzbek name -- not
// just the ~60 major organs that have a full hand-written description in
// EXPLANATIONS_UZ. Standard international Latin muscle/nerve components
// (e.g. "pollicis", "brevis") are rendered the way Uzbek anatomy texts use
// them: kept recognisable rather than force-translated into unnatural Uzbek.

const GLOSSARY:Record<string,string> = {
 "left":"chap",
 "right":"o’ng",
 "anterior":"oldingi",
 "posterior":"orqa",
 "superior":"yuqori",
 "inferior":"pastki",
 "medial":"medial",
 "lateral":"lateral",
 "middle":"o’rta",
 "upper":"yuqori",
 "lower":"pastki",
 "proximal":"proksimal",
 "distal":"distal",
 "superficial":"yuza",
 "deep":"chuqur",
 "internal":"ichki",
 "external":"tashqi",
 "dorsal":"orqa",
 "palmar":"kaft",
 "plantar":"kaft (oyoq)",
 "anterolateral":"oldingi-lateral",
 "posteromedial":"orqa-medial",
 "anteroposterior":"oldingi-orqa",
 "inferomedial":"pastki-medial",
 "laterobasal":"lateral-bazal",
 "mediobasal":"medial-bazal",
 "apicoposterior":"uchki-orqa",
 "antero":"oldingi",
 "postero":"orqa",
 "supra":"usti",
 "sub":"osti",
 "infra":"osti",
 "pre":"oldi",
 "post":"keyingi",
 "extra":"tashqi",
 "intra":"ichki",
 "main":"asosiy",
 "common":"umumiy",
 "proper":"xos",
 "free":"erkin",
 "true":"haqiqiy",
 "false":"yolg’on",
 "typical":"odatiy",
 "atypical":"noodatiy",
 "variant":"variant",
 "accessory":"qo’shimcha",
 "accessorius":"qo’shimcha",
 "great":"katta",
 "large":"katta",
 "small":"kichik",
 "little":"kichik",
 "big":"katta",
 "major":"katta",
 "minor":"kichik",
 "minimus":"eng kichik",
 "minimi":"kichik barmoq",
 "maximus":"eng katta",
 "longus":"uzun",
 "brevis":"qisqa",
 "longissimus":"eng uzun mushak",
 "magnus":"katta",
 "longi":"uzun",
 "short":"qisqa",
 "long":"uzun",
 "flat":"yassi",
 "round":"yumaloq",
 "straight":"to’g’ri",
 "oblique":"qiyshiq",
 "transverse":"ko’ndalang",
 "vertical":"vertikal",
 "horizontal":"gorizontal",
 "circumflex":"aylanma",
 "recurrent":"qaytar",
 "perforating":"teshuvchi",
 "communicating":"birlashtiruvchi",
 "ascending":"ko’tariluvchi",
 "descending":"tushuvchi",
 "terminal":"oxirgi",
 "terminalis":"oxirgi",
 "first":"birinchi",
 "second":"ikkinchi",
 "third":"uchinchi",
 "fourth":"to’rtinchi",
 "fifth":"beshinchi",
 "sixth":"oltinchi",
 "seventh":"yettinchi",
 "eighth":"sakkizinchi",
 "ninth":"to’qqizinchi",
 "tenth":"o’ninchi",
 "eleventh":"o‘n birinchi",
 "twelfth":"o‘n ikkinchi",
 "i":"I",
 "ii":"II",
 "iii":"III",
 "iv":"IV",
 "v":"V",
 "vi":"VI",
 "vii":"VII",
 "viii":"VIII",
 "ix":"IX",
 "x":"X",
 "artery":"arteriya",
 "arteries":"arteriyalar",
 "arterial":"arterial",
 "arteria":"arteriya",
 "vein":"vena",
 "veins":"venalar",
 "venous":"venoz",
 "vena":"vena",
 "venule":"venula",
 "branch":"tarmoq",
 "branches":"tarmoqlar",
 "trunk":"tanacha",
 "tree":"daraxtsimon tarmoq",
 "muscle":"mushak",
 "musculature":"mushak tizimi",
 "bone":"suyak",
 "bony":"suyakli",
 "nerve":"nerv",
 "nervous":"nerv",
 "ganglion":"gangliy",
 "plexus":"chigal",
 "organ":"organ",
 "organs":"organlar",
 "system":"tizim",
 "systemic":"sistemik",
 "gland":"bez",
 "tissue":"to’qima",
 "cartilage":"tog’ay",
 "cartilaginous":"tog’aysimon",
 "ligament":"boylam",
 "tendon":"pay",
 "tendinous":"paysimon",
 "fascia":"fassiya",
 "fasciae":"fassiyalar",
 "fascial":"fassial",
 "membrane":"parda",
 "membranous":"pardasimon",
 "capsule":"kapsula",
 "wall":"devor",
 "cavity":"bo’shliq",
 "cavitated":"bo’shliqli",
 "space":"bo’shliq",
 "sac":"xalta",
 "canal":"kanal",
 "duct":"yo’l",
 "ductus":"yo’l",
 "tract":"yo’l",
 "tracheobronchial":"traxeobronxial",
 "segment":"segment",
 "segmental":"segmentar",
 "subsegmental":"subsegmentar",
 "subsector":"quyi bo’lim",
 "sector":"bo’lim",
 "subdivision":"kichik bo’lim",
 "division":"bo’lim",
 "part":"qism",
 "parts":"qismlar",
 "portion":"qism",
 "zone":"zona",
 "region":"soha",
 "regions":"sohalar",
 "area":"hudud",
 "process":"o’simta",
 "head":"bosh",
 "tail":"dumcha",
 "body":"tanasi",
 "neck":"bo’yin",
 "base":"asos",
 "apex":"uchi",
 "apical":"uchki",
 "root":"ildiz",
 "arch":"ravoq",
 "ring":"halqa",
 "valve":"qopqoq",
 "sphincter":"sfinkter",
 "lumen":"bo’shliq",
 "floor":"tag",
 "layer":"qatlam",
 "lobe":"bo’lak",
 "lobar":"bo’lakli",
 "lobule":"bo’lakcha",
 "lobular":"bo’lakchali",
 "set":"to’plam",
 "cluster":"to’plam",
 "clusters":"to’plamlar",
 "group":"guruh",
 "network":"tarmoq",
 "entity":"struktura",
 "structure":"struktura",
 "component":"komponent",
 "complex":"kompleks",
 "junction":"birikma",
 "joint":"bo’g’im",
 "line":"chiziq",
 "linea":"chiziq",
 "plate":"plastinka",
 "disk":"disk",
 "sinus":"sinus",
 "fossa":"chuqurcha",
 "foramen":"teshik",
 "notch":"kertik",
 "incisure":"kertik",
 "crest":"tepacha",
 "tuber":"do’mboqcha",
 "spine":"tikan",
 "angle":"burchak",
 "abdomen":"qorin",
 "abdominal":"qorin",
 "thorax":"ko’krak qafasi",
 "thoracic":"ko’krak",
 "thoracis":"ko’krak",
 "pelvis":"chanoq",
 "pelvic":"chanoq",
 "back":"orqa",
 "chest":"ko’krak",
 "face":"yuz",
 "cheek":"yonoq",
 "jaw":"jag’",
 "mouth":"og’iz",
 "nose":"burun",
 "eye":"ko’z",
 "eyeball":"ko’z olmasi",
 "eyebrow":"qosh",
 "eyelid":"qovoq",
 "ear":"quloq",
 "tongue":"til",
 "tooth":"tish",
 "incisor":"kurak tish",
 "canine":"ko’z tishi",
 "molar":"kursak tish",
 "premolar":"kichik kursak tish",
 "gingiva":"milk",
 "palate":"tanglay",
 "uvula":"kichik til",
 "arm":"yelka-bilak",
 "forearm":"bilak",
 "hand":"qo’l",
 "wrist":"bilak bo’g’imi",
 "finger":"barmoq",
 "thumb":"bosh barmoq",
 "index":"ko’rsatkich barmoq",
 "shoulder":"yelka",
 "leg":"oyoq",
 "thigh":"son",
 "knee":"tizza",
 "foot":"oyoq panjasi",
 "toe":"oyoq barmog’i",
 "hip":"chanoq-son",
 "limb":"a’zo (oyoq-qo’l)",
 "skeleton":"skelet",
 "skeletal":"skelet",
 "skin":"teri",
 "integument":"teri qoplami",
 "integumentary":"teri qoplami",
 "hair":"soch",
 "hairs":"sochlar",
 "heart":"yurak",
 "cardiac":"yurak",
 "cardiovascular":"yurak-qon tomir",
 "myocardium":"miokard",
 "myocardial":"miokard",
 "pericardium":"perikard",
 "atrium":"bo’lma",
 "ventricle":"qorincha",
 "ventricular":"qorincha",
 "interventricular":"qorinchalararo",
 "mitral":"mitral",
 "tricuspid":"trikuspidal",
 "coronary":"tojsimon",
 "lung":"o’pka",
 "pulmonary":"o’pka",
 "pulmopleural":"o’pka-plevra",
 "bronchus":"bronx",
 "bronchial":"bronxial",
 "bronchopulmonary":"bronxo’pka",
 "trachea":"traxeya",
 "respiratory":"nafas olish",
 "esophagus":"qizilo’ngach",
 "esophageal":"qizilo’ngach",
 "stomach":"oshqozon",
 "gastric":"oshqozon",
 "gastro":"oshqozon",
 "gastrointestinal":"oshqozon-ichak",
 "intestine":"ichak",
 "duodenum":"o’n ikki barmoqli ichak",
 "ileum":"yonbosh ichak",
 "ileal":"yonbosh ichak",
 "ileocecal":"yonbosh-ko’richak",
 "ileocolic":"yonbosh-yo’g’on ichak",
 "colon":"yo’g’on ichak",
 "coli":"yo’g’on ichak",
 "colic":"yo’g’on ichak",
 "cecum":"ko’richak",
 "cecal":"ko’richak",
 "sigmoid":"sigmasimon",
 "rectum":"to’g’ri ichak",
 "rectal":"to’g’ri ichak",
 "appendix":"appendiks",
 "liver":"jigar",
 "hepatic":"jigar",
 "hepatovenous":"jigar-vena",
 "gallbladder":"o’t pufagi",
 "biliary":"o’t yo’llari",
 "pancreas":"oshqozon osti bezi",
 "pancreatic":"oshqozon osti bezi",
 "pancreaticobiliary":"oshqozon osti bezi-o’t yo’li",
 "pancreaticoduodenal":"oshqozon osti bezi-o’n ikki barmoqli ichak",
 "spleen":"taloq",
 "splenic":"taloq",
 "mesentery":"me’za",
 "mesenteric":"me’za",
 "mesocolon":"me’za (yo’g’on ichak)",
 "mesocolica":"me’za (yo’g’on ichak)",
 "mesoappendix":"me’za (appendiks)",
 "omentalis":"katta charvi",
 "peritoneum":"qorin parda",
 "peritoneal":"qorin parda",
 "epiploic":"charvi",
 "celiac":"chelyak",
 "coeliac":"chelyak",
 "kidney":"buyrak",
 "renal":"buyrak",
 "urinary":"siydik",
 "ureter":"siydik yo’li",
 "ureteric":"siydik yo’li",
 "urethra":"siydik chiqarish kanali",
 "bladder":"qop",
 "genital":"jinsiy",
 "testis":"moyak",
 "testicular":"moyak",
 "prostate":"prostata",
 "penis":"jinsiy a’zo",
 "seminal":"sperma",
 "epididymis":"epididimis",
 "glans":"bosh (a’zo)",
 "cavernosum":"g’ovaksimon tana",
 "cavernous":"g’ovaksimon",
 "spongiosum":"g’ovak tana",
 "brain":"miya",
 "cerebral":"bosh miya",
 "cerebellum":"miyacha",
 "cerebellar":"miyacha",
 "cerebelli":"miyacha",
 "brainstem":"miya sopi",
 "forebrain":"oldingi miya",
 "hindbrain":"orqa miya (bosh)",
 "midbrain":"o’rta miya",
 "diencephalon":"oraliq miya",
 "telencephalon":"yakuniy miya",
 "metencephalon":"orqa miya (metensefalon)",
 "pons":"pons (ko’prik)",
 "medulla":"uzunchoq miya",
 "oblongata":"uzunchoq miya",
 "thalamus":"talamus",
 "hypothalamus":"gipotalamus",
 "hypothalamic":"gipotalamik",
 "epithalamus":"epitalamus",
 "pituitary":"gipofiz",
 "hippocampus":"gippokamp",
 "hippocampal":"gippokamp",
 "amygdala":"amigdala",
 "pineal":"epifiz",
 "insula":"orolcha",
 "insular":"orolcha",
 "gyrus":"g’ijim",
 "sulcus":"egatcha",
 "frontal":"peshona",
 "parietal":"tepa",
 "temporal":"chakka",
 "occipital":"ensa",
 "frontobasal":"peshona-bazal",
 "postcentral":"markazdan keyingi",
 "precentral":"markazdan oldingi",
 "paracentral":"markaz atrofi",
 "callosum":"nasha tanacha (corpus callosum)",
 "callosomarginal":"nasha tanacha chekka",
 "commissure":"komissura",
 "decussation":"kesishma",
 "fornix":"forniks",
 "habenula":"habenula",
 "globus":"globus",
 "pallidus":"pallidus",
 "putamen":"putamen",
 "caudate":"dumli yadro",
 "nucleus":"yadro",
 "nuclear":"yadroviy",
 "gray":"kulrang",
 "white":"oq",
 "matter":"modda",
 "substance":"modda",
 "tectum":"tektum",
 "tegmentum":"tegmentum",
 "peduncle":"oyoqcha",
 "interpeduncular":"oyoqchalar orasi",
 "thalamogeniculate":"talamo-genikulyat",
 "thalamoperforating":"talamo-teshuvchi",
 "aqueduct":"suv yo’li",
 "circumventricular":"qorinchalar atrofi",
 "neuraxis":"nerv o’qi",
 "archicortex":"arxikorteks",
 "cortex":"po’stloq",
 "cortical":"po’stloq",
 "corticomedullary":"po’stloq-medulla",
 "subcortex":"po’stloq osti",
 "angular":"burchak",
 "supramarginal":"chekka usti",
 "parahippocampal":"gippokamp atrofi",
 "cingulate":"singulat",
 "choroid":"tomirli parda",
 "choroidal":"tomirli parda",
 "autonomic":"avtonom",
 "parasympathetic":"parasimpatik",
 "oculomotor":"ko’z harakat",
 "trigeminal":"uch shoxli",
 "auriculotemporal":"quloq-chakka",
 "infratrochlear":"g’altak osti",
 "nasociliary":"burun-kirpik",
 "ophthalmic":"ko’z",
 "optic":"ko’ruv",
 "vocal":"ovoz",
 "vocalis":"ovoz",
 "larynx":"halqum (gırtlak)",
 "laryngeal":"gırtlak",
 "laryngopharynx":"gırtlak-tomoq",
 "pharynx":"tomoq",
 "pharyngeal":"tomoq",
 "cricoid":"uzuksimon",
 "cricothyroid":"uzuk-qalqonsimon",
 "crico":"uzuksimon",
 "thyroid":"qalqonsimon bez",
 "thyro":"qalqonsimon",
 "arytenoid":"qoshiqsimon",
 "epiglottis":"nafas qopqog’i",
 "epiglottic":"nafas qopqog’i",
 "elasticus":"elastik",
 "corniculate":"shoxsimon",
 "salpingopharyngeus":"nay-tomoq mushagi",
 "stylopharyngeus":"stilo-tomoq mushagi",
 "palatopharyngeus":"tanglay-tomoq mushagi",
 "constrictor":"siquvchi mushak",
 "palatine":"tanglay",
 "palatini":"tanglay",
 "curtain":"parda",
 "faucial":"tomoq bo’g’izi",
 "hyoid":"til osti suyagi",
 "hyo":"til osti",
 "geniohyoid":"iyak-til osti mushagi",
 "stylohyoid":"stilo-til osti mushagi",
 "mylohyoid":"milk-til osti mushagi",
 "omohyoid":"kurak-til osti mushagi",
 "thyrohyoid":"qalqon-til osti mushagi",
 "infrahyoid":"til osti pastki",
 "suprahyoid":"til osti ustki",
 "genioglossus":"iyak-til mushagi",
 "hyoglossus":"til osti-til mushagi",
 "sternohyoid":"ko’krak-til osti mushagi",
 "sternothyroid":"ko’krak-qalqon mushagi",
 "platysma":"bo’yin yassi mushagi",
 "sternocleidomastoid":"ko’krak-o’mrov-so’rg’ichsimon mushagi",
 "digastric":"ikki qorincha mushagi",
 "lacrimal":"ko’z yosh",
 "nasolacrimal":"burun-ko’z yosh",
 "nasal":"burun",
 "ethmoid":"g’alvirsimon",
 "ethmoidal":"g’alvirsimon",
 "sphenoid":"ponasimon",
 "maxilla":"yuqori jag’ suyagi",
 "maxillary":"yuqori jag’",
 "mandible":"pastki jag’ suyagi",
 "mandibular":"pastki jag’",
 "zygomatic":"yonoq suyagi",
 "vomer":"ochlik suyagi",
 "basicranium":"bosh suyagi asosi",
 "basicranial":"bosh suyagi asosi",
 "neurocranium":"miya qutisi",
 "viscerocranium":"yuz suyagi",
 "skull":"bosh suyagi",
 "orbit":"ko’z kosasi",
 "orbital":"ko’z kosasi",
 "sclera":"oqsil parda",
 "cornea":"shox parda",
 "iris":"rangdor parda",
 "ciliary":"kipriksimon",
 "ciliaris":"kipriksimon",
 "lens":"gavhar",
 "retina":"to’r parda",
 "vitreous":"shishasimon tana",
 "chamber":"kamera",
 "conjunctiva":"shilliq parda",
 "palpebrae":"qovoqlar",
 "vertebra":"umurtqa",
 "vertebrae":"umurtqalar",
 "vertebral":"umurtqa",
 "intervertebral":"umurtqalararo",
 "cervical":"bo’yin",
 "cervicis":"bo’yin",
 "lumbar":"bel",
 "lumborum":"bel",
 "sacral":"dumg’aza",
 "sacrum":"dumg’aza suyagi",
 "coccygeus":"dumbaqa mushagi",
 "atlas":"atlant umurtqasi",
 "axis":"aylanuvchi umurtqa",
 "rib":"qovurg’a",
 "costal":"qovurg’a",
 "costarum":"qovurg’alar",
 "intercostal":"qovurg’alararo",
 "subcostal":"qovurg’a osti",
 "sternum":"to’sh suyagi",
 "sternal":"to’sh suyagi",
 "sternocostal":"to’sh-qovurg’a",
 "xiphoid":"xanjarsimon o’simta",
 "manubrium":"to’sh suyagi dastasi",
 "clavicle":"o’mrov suyagi",
 "clavicular":"o’mrov",
 "scapula":"kurak suyagi",
 "scapulae":"kurak suyaklari",
 "scapular":"kurak",
 "humerus":"yelka suyagi",
 "humeral":"yelka",
 "brachium":"yelka",
 "brachial":"yelka",
 "brachii":"yelka",
 "brachialis":"yelka mushagi",
 "brachiocephalic":"yelka-bosh",
 "brachioradialis":"yelka-bilak mushagi",
 "biceps":"ikki boshli mushak",
 "triceps":"uch boshli mushak",
 "coracobrachialis":"korakobrakial mushak",
 "deltoid":"delta mushagi",
 "radius":"kaft suyagi (radius)",
 "radial":"radial",
 "radialis":"radial",
 "ulna":"tirsak suyagi",
 "ulnar":"tirsak",
 "ulnaris":"tirsak",
 "pronator":"pronator mushagi",
 "supinator":"supinator mushagi",
 "carpal":"bilak suyagi (karpal)",
 "carpi":"bilak",
 "metacarpal":"kaft suyagi",
 "phalanx":"falanga",
 "digital":"barmoq",
 "digiti":"barmoq",
 "digitorum":"barmoqlar",
 "palmaris":"kaft mushagi",
 "opponens":"qarshi qo’yuvchi mushak",
 "abductor":"uzoqlashtiruvchi mushak",
 "adductor":"yaqinlashtiruvchi mushak",
 "flexor":"bukuvchi mushak",
 "extensor":"yozuvchi mushak",
 "interossei":"oraliq mushaklar",
 "interosseous":"oraliq",
 "lumbrical":"chuvalchangsimon mushak",
 "lumbricals":"chuvalchangsimon mushaklar",
 "pollicis":"bosh barmoq",
 "indicis":"ko’rsatkich barmoq",
 "hallucis":"bosh oyoq barmog’i",
 "pisiform":"no’xatsimon suyak",
 "scaphoid":"qayiqsimon suyak",
 "lunate":"oysimon suyak",
 "triquetral":"uch qirrali suyak",
 "trapezium":"katta ko’p qirrali suyak",
 "trapezoid":"kichik ko’p qirrali suyak",
 "capitate":"boshsimon suyak",
 "hamate":"ilmoqsimon suyak",
 "navicular":"qayiqsimon suyak",
 "cuboid":"kubsimon suyak",
 "cuneiform":"ponasimon suyak",
 "talus":"to’piq suyagi",
 "calcaneus":"tovon suyagi",
 "calcaneal":"tovon",
 "metatarsal":"oyoq panjasi suyagi",
 "tarsal":"tarsal",
 "pedis":"oyoq panjasi",
 "femur":"son suyagi",
 "femoral":"son",
 "femoris":"son",
 "patella":"tizza qopqog’i",
 "patellar":"tizza qopqog’i",
 "popliteal":"tizza osti",
 "popliteus":"tizza osti mushagi",
 "tibia":"katta boldir suyagi",
 "tibial":"boldir",
 "tibialis":"boldir mushagi",
 "fibula":"kichik boldir suyagi",
 "fibular":"kichik boldir",
 "fibularis":"kichik boldir mushagi",
 "genicular":"tizza",
 "iliac":"yonbosh",
 "iliacus":"yonbosh mushagi",
 "iliotibial":"yonbosh-boldir",
 "iliolumbar":"yonbosh-bel",
 "iliococcygeus":"yonbosh-dumbaqa mushagi",
 "ischial":"o’tirg’ich",
 "obturator":"tiqinsimon mushak",
 "puborectalis":"qov-to’g’ri ichak mushagi",
 "pubococcygeus":"qov-dumbaqa mushagi",
 "pubic":"qov",
 "pubis":"qov suyagi",
 "symphysis":"birikma (simfiz)",
 "gluteal":"dumba",
 "gluteus":"dumba mushagi",
 "psoas":"bel mushagi",
 "quadratus":"to’rtburchak mushak",
 "quadriceps":"to’rt boshli mushak",
 "sartorius":"tikuvchi mushak",
 "gracilis":"ingichka mushak",
 "pectineus":"taroqsimon mushak",
 "gemellus":"egizak mushak",
 "piriformis":"noksimon mushak",
 "obliquus":"qiyshiq mushak",
 "rectus":"to’g’ri mushak",
 "pectoralis":"ko’krak mushagi",
 "pectoral":"ko’krak",
 "serratus":"arrasimon mushak",
 "rhomboid":"romsimon mushak",
 "trapezius":"trapetsiyasimon mushak",
 "levator":"ko’taruvchi mushak",
 "levatores":"ko’taruvchi mushaklar",
 "scalene":"lestnitsasimon mushak",
 "scalenus":"lestnitsasimon mushak",
 "splenius":"yelpig’ichsimon mushak",
 "semispinalis":"yarim-tikanli mushak",
 "multifidus":"ko’p bo’lakli mushak",
 "interspinales":"tikanlararo mushaklar",
 "interspinalis":"tikanlararo mushak",
 "intertransversarii":"ko‘ndalang o‘simtalar orasidagi mushaklar",
 "intertransversarius":"ko‘ndalang o‘simtalar orasidagi mushak",
 "iliocostalis":"yonbosh-qovurg’a mushagi",
 "anconeus":"tirsak mushagi",
 "soleus":"kambalasimon mushak",
 "gastrocnemius":"ikki boshli boldir mushagi",
 "plantaris":"kaft mushagi (oyoq)",
 "semimembranosus":"yarim pardali mushak",
 "semitendinosus":"yarim payli mushak",
 "sesamoid":"sezamsimon suyak",
 "coracoid":"qarg’a tumshug’isimon o’simta",
 "subscapular":"kurak osti",
 "subscapularis":"kurak osti mushagi",
 "infraspinatus":"kurak osti chuqurchasi mushagi",
 "supraspinatus":"kurak usti chuqurchasi mushagi",
 "teres":"silindrsimon mushak",
 "hypothenar":"kaft chekka do’mboqchasi",
 "thenar":"kaft do’mboqchasi",
 "articular":"bo’g’im",
 "articulation":"bo’g’im",
 "crural":"boldir",
 "cubital":"tirsak",
 "axillary":"qo’ltiq",
 "axilla":"qo’ltiq",
 "subclavian":"o’mrov osti",
 "subclavius":"o’mrov osti mushagi",
 "suprascapular":"kurak usti",
 "acromial":"akromial (yelka uchi)",
 "acromion":"akromion",
 "thoraco":"ko’krak",
 "thoracodorsal":"ko’krak-orqa",
 "musculophrenic":"mushak-diafragma",
 "phrenic":"diafragma",
 "diaphragm":"diafragma",
 "epigastric":"epigastral (qorin usti)",
 "gastroepiploic":"oshqozon-charvi",
 "gastroduodenal":"oshqozon-o’n ikki barmoqli ichak",
 "saphenous":"teri osti venasi",
 "peroneal":"kichik boldir",
 "sural":"boldir (surall)",
 "hallux":"bosh oyoq barmog’i",
 "jugular":"bo’yinturuq (vena)",
 "carotid":"uyqu (arteriya)",
 "azygos":"toq vena",
 "hemiazygos":"yarim toq vena",
 "portal":"darvoza (portal)",
 "suprarenal":"buyrak usti",
 "adrenal":"buyrak usti bezi",
 "gonadal":"jinsiy bez",
 "ovarian":"tuxumdon",
 "inguinal":"chov",
 "perineal":"oraliq",
 "perineum":"oraliq",
 "anal":"anal",
 "ani":"anal",
 "vascular":"tomir",
 "vasculature":"tomirlar tizimi",
 "lymphatic":"limfa",
 "lymph":"limfa",
 "node":"tugun",
 "nodes":"tugunlar",
 "vessel":"tomir",
 "vessels":"tomirlar",
 "capillary":"kapillyar",
 "capillaries":"kapillyarlar",
 "musculoskeletal":"mushak-skelet",
 "connective":"biriktiruvchi",
 "endocrine":"endokrin",
 "exocrine":"ekzokrin",
 "reproductive":"reproduktiv",
 "sensory":"sezgi",
 "alimentary":"ovqat hazm qilish",
 "digestive":"ovqat hazm qilish",
 "circulatory":"qon aylanish",
 "peripheral":"periferik",
 "central":"markaziy",
 "spinal":"orqa miya",
 "spinalis":"orqa miya mushagi",
 "cord":"ip (kord)",
 "dura":"qattiq parda",
 "mater":"parda",
 "arachnoid":"o’rgimchak parda",
 "pia":"yumshoq parda",
 "meninges":"miya pardalari",
 "subarachnoid":"o’rgimchak parda osti",
 "epidermis":"epidermis (teri yuza qatlami)",
 "dermis":"derma",
 "hypodermis":"teri osti qatlami",
 "of":"ning",
 "with":"bilan",
 "to":"ga",
 "human":"inson",
 "anatomical":"anatomik",
 "physical":"jismoniy",
 "immaterial":"nomoddiy",
 "material":"moddiy",
 "boundary":"chegara",
 "content":"tarkib",
 "continuity":"uzluksizlik",
 "apparatus":"apparat",
 "appendage":"o’simta",
 "appendicular":"oyoq-qo’l",
 "axial":"o’qsimon",
 "irregular":"notekis",
 "hollow":"bo’sh",
 "solid":"qattiq",
 "nonparenchymatous":"parenximasiz",
 "parenchymatous":"parenximali",
 "parenchyma":"parenxima",
 "nonskeletal":"skeletsiz",
 "fusiform":"urchuqsimon",
 "mucoid":"shilliqsimon",
 "serous":"seroz",
 "septal":"septal",
 "septum":"to’siq",
 "raphe":"chok chizig’i",
 "trigone":"uchburchak (trigon)",
 "conus":"konus",
 "colliculus":"do’mboqcha",
 "papillary":"so’rg’ichsimon",
 "papilla":"so’rg’ich",
 "cusp":"qanotcha",
 "leaflet":"bargcha",
 "leaf":"bargcha",
 "chiasm":"kesishma",
 "veli":"parda",
 "vela":"parda",
 "tentorium":"chodircha",
 "girdle":"kamar",
 "extrahepatic":"jigardan tashqari",
 "intrahepatic":"jigar ichi",
 "intrapulmonary":"o’pka ichi",
 "intracranial":"bosh suyagi ichi",
 "outflow":"chiqish yo’li",
 "inflow":"kirish yo’li",
 "tributary":"quyiluvchi tarmoq",
 "collateral":"yordamchi (kollateral)",
 "anastomosis":"anastomoz",
 "pathway":"yo’l",
 "innermost":"eng ichki",
 "investing":"o’rovchi",
 "loose":"bo’sh",
 "basal":"bazal",
 "secondary":"ikkilamchi",
 "capitis":"bosh (mushagi)",
 "compartment":"bo’lim",
 "hemisphere":"yarim shar",
 "mediastinum":"ko’krak oralig’i",
 "side":"tomon",
 "aorta":"aorta",
 "pontine":"pons",
 "lingular":"til bo’lakchasi",
 "intermediate":"oraliq",
 "median":"o’rta",
 "vastus":"keng mushak",
 "rotator":"aylantiruvchi mushak",
 "pericallosal":"nasha tanacha atrofi",
 "colli":"bo’yin",
 "intrinsic":"ichki (o’z)",
 "stria":"chiziq",
 "check":"tekshirish",
 "costocervical":"qovurg’a-bo’yin",
 "medius":"o’rta",
 "pudendal":"jinsiy (pudendal)",
 "geniculate":"genikulyat",
 "lateralis":"lateral",
 "tensor":"tarang tortuvchi mushak",
 "thyrocervical":"qalqonsimon-bo’yin",
 "aortic":"aorta",
 "column":"ustun",
 "jejunum":"ochiq ichak",
 "fibrous":"tolali",
 "superioris":"yuqori",
 "marginal":"chekka",
 "prefrontal":"peshona oldi",
 "basilic":"bazilik (vena)",
 "cranial":"bosh suyagi",
 "postcommunicating":"birlashmadan keyingi",
 "cardinal":"asosiy",
 "corpus":"tana",
 "extrinsic":"tashqi",
 "postvertebral":"umurtqa orqasi",
 "retinaculum":"ushlagich (retinakulum)",
 "thymus":"timus",
 "in":"da",
 "vivo":"tirik organizmda",
 "taenia":"lentasimon tuzilma",
 "arcuate":"yoysimon",
 "princeps":"asosiy",
 "aryepiglotticus":"gırtlaq qopqog’i mushagi",
 "cephalic":"bosh tomon (vena)",
 "corona":"toj",
 "deferent":"chiqaruvchi (naycha)",
 "dorsalis":"orqa",
 "lata":"keng (fassiya)",
 "tertius":"uchinchi",
 "profundus":"chuqur",
 "superficialis":"yuza",
 "concha":"chig’anoq",
 "intermediomedial":"oraliq-medial",
 "canaliculus":"kanalcha",
 "lake":"ko’lcha",
 "lamina":"plastinka",
 "alar":"qanotsimon",
 "antebrachial":"bilak",
 "externus":"tashqi",
 "internus":"ichki",
 "polar":"qutb",
 "pterygomandibular":"qanotsimon-jag’",
 "vesicle":"pufakcha",
 "cage":"qafas",
 "splenial":"taloq",
 "medullaris":"medulla",
 "sublingual":"til osti",
 "submandibular":"jag’ osti",
 "supratrochlear":"g’altak usti",
 "latae":"keng",
 "transversus":"ko’ndalang mushak",
 "trochlear":"g’altak",
 "intermedius":"oraliq",
 "medialis":"medial",
 "osseous":"suyakli",
 "precommunicating":"birlashmadan oldingi",
 "precuneal":"prekuneus oldi",
 "breves":"qisqa",
 "vermian":"chuvalchang (miyacha)",
 "suspensory":"osuvchi",
 "temporo":"chakka",
 "trochlea":"g’altak",
 "subsuperior":"yuqori osti",
 "suboccipital":"ensa osti",
 "basilar":"baziler",
 "bile":"o’t",
 "circle":"halqa",
 "cell":"hujayra",
 "dorsum":"orqa yuza",
 "heterogeneous":"xilma-xil",
 "cava":"kovak",
 "hemiliver":"jigar yarmi",
 "formation":"formatsiya",
 "limbic":"limbik",
 "salivary":"so’lak",
 "neural":"nerv",
 "visceral":"ichki a’zo",
 "caval":"kovak vena",
 "subendocardial":"endokard osti",
 "conduit":"o’tkazgich",
 "caudal":"dumsimon",
 "cystic":"o’t pufagi",
 "diagonal":"diagonal",
 "ocular":"ko’z",
 "floating":"suzuvchi",
 "alba":"oq",
 "lip":"lab",
 "mammillary":"so’rg’ichsimon tana",
 "mons":"do’mboq",
 "pneumatized":"havo bilan to’lgan",
 "prevertebral":"umurtqa oldi",
 "facial":"yuz",
 "oesophageal":"qizilo’ngach",
 "soft":"yumshoq",
 "subaortic":"aorta osti",
 "epithelium":"epiteliy",
 "subdivisionof":"ning bo’lagi",
 "supreme":"eng yuqori",
 "libera":"erkin",
 "cinereum":"kulrang",
 "uvular":"kichik til",
};

const MUTATE_Q = new Set(["bo’shliq", "chanoq", "chig’anoq", "chiziq", "do’mboq", "oraliq", "oyoq", "po’stloq", "qopqoq", "qo’ltiq", "quloq", "ravoq", "tarmoq", "tomoq", "to’piq", "to’siq", "uzunchoq", "yumaloq"]);
const MUTATE_K = new Set(["bo’lak", "burchak", "buyrak", "ichak", "kovak", "ko’krak", "ko’richak", "kurak", "kursak", "moyak", "mushak", "qovoq", "suyak", "taloq", "teshik", "tirsak", "yurak"]);
const POSTPOSITIVE = new Set(["breves", "brevis", "communis", "dorsalis", "externus", "internus", "lateralis", "longus", "magnus", "major", "maximus", "medialis", "medius", "minimus", "minor", "princeps", "profundus", "superficialis", "superioris", "tertius"]);
const SIDE_ROOTS = new Set(["chap", "lateral", "medial", "oldingi", "orqa", "o’ng", "o’rta", "pastki", "yuqori"]);
const GENERIC_SUPPRESS:Record<string,string> = {"bone": "suya", "muscle": "musha", "artery": "arteriya", "vein": "vena", "body": "tana", "gland": "bez", "nerve": "nerv", "ligament": "boylam", "joint": "bo’g’im", "vessel": "tomir", "valve": "qopqoq", "organ": "organ", "tendon": "pay", "tooth": "tish", "nucleus": "yadro", "finger": "barmoq", "thumb": "barmoq", "toe": "barmo", "vertebra": "umurtqa", "vertebral": "umurtqa", "mater": "parda", "process": "o’simta"};

const VOWELS = new Set(['a','e','i','o','u','A','E','I','O','U']);

function possessive(nounUz:string):string{
 if(!nounUz)return nounUz;
 if(nounUz.endsWith('q')&&MUTATE_Q.has(nounUz))return nounUz.slice(0,-1)+"g'i";
 if(nounUz.endsWith('k')&&MUTATE_K.has(nounUz))return nounUz.slice(0,-1)+'gi';
 if(VOWELS.has(nounUz[nounUz.length-1]))return nounUz+'si';
 return nounUz+'i';
}

function translateWord(w:string):string{
 if(w.includes('-'))return w.split('-').map(p=>p?translateWord(p):p).join('-');
 return GLOSSARY[w.toLowerCase()]??w;
}

function appendWord(out:string[],rawToken:string,translated:string){
 const lw=rawToken.toLowerCase();
 const suppress=GENERIC_SUPPRESS[lw];
 if(out.length&&suppress&&out[out.length-1].toLowerCase().includes(suppress))return;
 out.push(translated);
}

function translatePhrase(phrase:string):string{
 const tokens=phrase.split(' ').filter(Boolean);
 if(tokens.length>=2&&POSTPOSITIVE.has(tokens[tokens.length-1].toLowerCase())){
  const adjRaw=tokens.pop()!;
  const adjUz=translateWord(adjRaw);
  const rest:string[]=[];
  for(const t of tokens)appendWord(rest,t,translateWord(t));
  const insertAt=rest.length&&SIDE_ROOTS.has(rest[0].toLowerCase())?1:0;
  rest.splice(insertAt,0,adjUz);
  return rest.join(' ');
 }
 const out:string[]=[];
 for(const t of tokens)appendWord(out,t,translateWord(t));
 return out.join(' ');
}

/** Translate a single BodyParts3D structure/concept name into Uzbek. */
export function translateAnatomyName(name:string):string{
 const trimmed=name.trim();
 const ofIndex=trimmed.indexOf(' of ');
 if(ofIndex!==-1){
  const head=trimmed.slice(0,ofIndex);
  const tail=trimmed.slice(ofIndex+4);
  const headUz=translatePhrase(head);
  const tailUz=translateAnatomyName(tail);
  const parts=headUz.split(' ');
  parts[parts.length-1]=possessive(parts[parts.length-1]);
  return `${tailUz}ning ${parts.join(' ')}`;
 }
 return translatePhrase(trimmed);
}

/** Capitalize the first letter, for display as a title. */
export function capitalizeName(s:string):string{
 return s?s[0].toUpperCase()+s.slice(1):s;
}
